site_name: General Bikeshare Feed Specification
site_url: https://gbfs.org
repo_url: https://github.com/MobilityData/gbfs

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

theme:
  logo_light_mode: assets/venn.svg
  logo_dark_mode: assets/library-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  name: material
  custom_dir: overrides
  favicon: assets/venn-black.svg
  font:
    text: SF Pro
    code: SF Mono
  features:
      - navigation.tabs
      - navigation.indexes
      - navigation.top
      # - navigation.instant
      # - navigation.instant.progress
      - toc.integrate
      - content.tabs.link
      - search.suggest
  custom_dir: theme_overrides
extra_css:
  - assets/stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-N7RXJMH84M
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to track visits, stored anonymously. With your consent, you're helping us to make our documentation better. See our <a href="https://mobilitydata.org/privacy-policy/">Privacy Policy</a>.
    actions:
        - accept
        - reject
        - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://share.mobilitydata.org/slack
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        'home.md': 'index.md'
        'major-change-proposals.md': 'specification/change-proposals.md'
        'tools-services.md': 'toolbox/index.md'
        'faq.md': 'learn/faq.md'
        'about.md': 'participate.md'
  - i18n:
      docs_structure: folder
      reconfigure_search: false
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true

nav:
- Home: index.md
- Specification:
  - specification/index.md
  - Current Version: specification/reference.md
  - Change Proposals: specification/change-proposals.md
  - Governance Process: specification/process.md
- Toolbox: 
  - toolbox/index.md
  - Community Tools and Resources: toolbox/resources.md
  - Glossary: toolbox/glossary.md
- Learn:
  - learn/index.md
  - White Papers: 
    - learn/white-papers/index.md
    - Data Policy: learn/white-papers/data-policy.md
    - Data Policy Europe: learn/white-papers/data-policy-europe.md
  - FAQ: learn/faq.md
- Participate: participate.md
- Implementation Guide: learn/guide.md