site_name: General Bikeshare Feed Specification
site_url: https://gbfs.org
repo_url: https://github.com/MobilityData/gbfs

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

theme:
  language: en
  locale: en
  logo_light_mode: assets/venn.svg
  logo_dark_mode: assets/venn.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  name: material
  custom_dir: overrides
  favicon: assets/venn-black.svg
  font:
    text: SF Pro
    code: SF Mono
  features:
      - navigation.tabs
      - navigation.indexes
      - navigation.top
      # - navigation.instant
      # - navigation.instant.progress
      - toc.integrate
      - content.tabs.link
      - search.suggest
  custom_dir: theme_overrides
  icon:
    alternate: octicons/globe-24
extra_css:
  - assets/stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-N7RXJMH84M
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to track visits, stored anonymously. With your consent, you’re helping us improve this documentation. See our <a href="https://mobilitydata.org/privacy-policy/">Privacy Policy</a>.
    actions:
        - accept
        - reject
        - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MobilityData
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mobilitydata
    - icon: fontawesome/brands/slack
      link: https://share.mobilitydata.org/slack
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        'home.md': 'index.md'
        'major-change-proposals.md': 'https://github.com/MobilityData/gbfs/issues'
        'tools-services.md': 'tools.md'
        'faq.md': 'specification/faq.md'
        'about.md': 'community.md'
  - external-markdown
  - i18n:
      docs_structure: folder
      reconfigure_search: false
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            Get started: Premiers pas
            Documentation: Documentation
            Current Version: Version actuelle
            Governance Process: Processus de gouvernance
            Data Quality: Qualité des données
            Data Policy: Politique en matière de données
            FAQ: FAQ
            Tools: Outils
            Community: Communauté
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Hogar
            Get started: Primeros pasos
            Documentation: Documentación
            Current Version: Versión actual
            Governance Process: Proceso de Gobernanza
            Data Quality: Calidad de los datos
            Data Policy: Política de datos
            FAQ: FAQ
            Tools: Herramientas
            Community: Comunidad

nav:
  - Home: index.md
  - Get started: guide.md
  - Documentation:
    - specification/index.md
    - Current Version: specification/reference.md
    - Governance Process: specification/process.md
    - Data Quality: specification/data-quality.md
    - Data Policy: specification/data-policy.md
    - FAQ: specification/faq.md
  - Tools: tools.md
  - Community: community.md
