name: Check Website returns 200, 301 or 302

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Update STAGING website on server
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 5 minutes
        run: sleep 300

      - name: Check HTTP Status Code
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://staging.gbfs.org/)
          if [[ "$STATUS_CODE" != 200 && "$STATUS_CODE" != 301 && "$STATUS_CODE" != 302 ]]; then
              echo "Error: Website returned status code $STATUS_CODE"
              exit 1
          fi
          echo "Website is up and returned $STATUS_CODE"
