name: Add issues project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/MobilityData/projects/58
          github-token: ${{ secrets.GBFS_REPOS_CURRENT_STATUS }}
